fixing workflow coverage badge issues

diff --git a/.github/workflows/coverage-badge.yml b/.github/workflows/coverage-badge.yml
--- a/.github/workflows/coverage-badge.yml
+++ b/.github/workflows/coverage-badge.yml
@@ -3,9 +3,8 @@ name: Generate and Publish Coverage Badge
 on:
   pull_request:
     branches:
-        - main
+      - main
     paths:
-      - "backend/**"
       - "backend/**"
       - ".github/workflows/coverage-badge.yml"
       - README.md
@@ -43,7 +42,6 @@ jobs:
 
       - name: Copy badge to docs (Pages directory)
         run: |
-          mkdir -p ../docs
           cp coverage-badge.svg ../docs/coverage-badge.svg
           # htmlcov will have a .gitignore by default
           [ -f htmlcov/.gitignore ] && rm htmlcov/.gitignore
@@ -51,10 +49,12 @@ jobs:
 
       - name: Commit and push badge to docs
         run: |
+          # checkout to the src branch of the pull request
+          git checkout ${{ github.head_ref || github.ref_name }}
           git config --global user.email "actions@github.com"
           git config --global user.name "github-actions"
           cd ..
           git add docs/{coverage-badge.svg,htmlcov}
-          # Avoid failing if there's no change
-          git commit -m "Update coverage badge [skip ci] and report" || exit 0
+          # avoid failing if there's no change
+          git commit -m "update coverage badge [skip ci] and report" || exit 0
           git push
